# Generated by Django 6.0.3 on 2026-03-18 13:04 (order corrected)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_clinician_created_at_clinician_updated_at_and_more"),
    ]

    operations = [
        # 1. Create BodyPart first (SnomedEntity depends on it)
        migrations.CreateModel(
            name="BodyPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details about what this body part includes.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        # 2. Create SnomedEntity before touching Symptom
        migrations.CreateModel(
            name="SnomedEntity",
            fields=[
                (
                    "snomed_cid",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "fsn",
                    models.CharField(
                        help_text="Fully Specified Name, e.g. 'Hypertensive disorder, systemic arterial (disorder)'",
                        max_length=500,
                    ),
                ),
                ("umls_cui", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("finding", "Finding/Symptom"),
                            ("procedure", "Procedure"),
                            ("body_structure", "Body Structure"),
                            ("other", "Other"),
                        ],
                        default="finding",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body_parts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="snomed_entities",
                        to="clinical.bodypart",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SNOMED Entities",
                "ordering": ["fsn"],
            },
        ),
        # 3. Add snomed_entity FK to Symptom (nullable so existing rows survive)
        migrations.AddField(
            model_name="symptom",
            name="snomed_entity",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="symptoms",
                to="clinical.snomedentity",
            ),
        ),
        # 4. Drop the old free-text code columns
        migrations.RemoveField(model_name="symptom", name="code"),
        migrations.RemoveField(model_name="symptom", name="code_system"),
        migrations.RemoveField(model_name="symptom", name="description"),
        # 5. Make snomed_entity non-nullable now that no old columns hold data
        migrations.AlterField(
            model_name="symptom",
            name="snomed_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="symptoms",
                to="clinical.snomedentity",
            ),
        ),
    ]
