"""
Generated by Django on 2026-03-22

This migration:
1. Removes the old 'is_under_processing' field
2. Adds the new 'locked' field with default=True
3. Sets locked=False for all existing records
"""

from django.db import migrations, models


def unlock_existing_records(apps, schema_editor):
    """Set locked=False for all existing Radiology records."""
    Radiology = apps.get_model('diagnostics', 'Radiology')
    Radiology.objects.all().update(locked=False)


def lock_all_records(apps, schema_editor):
    """Reverse: Set locked=True for all records (for migration rollback)."""
    Radiology = apps.get_model('diagnostics', 'Radiology')
    Radiology.objects.all().update(locked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '__PREVIOUS_MIGRATION__'),  # Replace with actual previous migration
    ]

    operations = [
        # Remove old field
        migrations.RemoveField(
            model_name='radiology',
            name='is_under_processing',
        ),
        # Add new field
        migrations.AddField(
            model_name='radiology',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        # Unlock existing records
        migrations.RunPython(
            unlock_existing_records,
            reverse_code=lock_all_records,
        ),
    ]
