# Generated by Django 6.0.3 on 2026-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "diagnostics",
            "0002_lab_created_at_lab_updated_at_radiology_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="radiology",
            name="locked",
            field=models.BooleanField(default=True),
        ),
    ]
